platform :ios, '14.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

generated_xcconfig = File.join(File.dirname(__FILE__), 'Flutter', 'Generated.xcconfig')
flutter_root = File.read(generated_xcconfig).match(/FLUTTER_ROOT\=(.*)/)[1]
require File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  install_all_flutter_pods(File.dirname(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
